//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace samotoyalka.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int Код { get; set; }
        public string ФИО { get; set; }
        public int Курс { get; set; }
        public string Почта { get; set; }
    
        public virtual Курсы Курсы { get; set; }
    }
}
